import { useState, useEffect, useRef } from 'react';
import Head from 'next/head';

import Header from '../components/Header';
import Cards from '../components/Cards';
import Video from '@/components/Video';
import Photos from '@/components/Photos';

import styles from '@/styles/Home.module.scss';

export default function Home() {
  const [headerShowed, setHeaderShowed] = useState(true);
  const videoElement = useRef();
  const photosElement = useRef();
  const scrollIntoPhotos = useRef(true);

  const handleScroll = () => {
    const videoHeight = videoElement.current.clientHeight;
    const videoPositionTop = videoElement.current.offsetTop;
    const windowHeight = window.innerHeight;
    const windowPosition = window.scrollY;

    handleHeaderShowed(windowPosition);
    handleVidePlay(videoHeight, videoPositionTop, windowHeight, windowPosition);
  };

  const handleSize = () => {
    const videoHeight = videoElement.current.clientHeight;
    const videoPositionTop = videoElement.current.offsetTop;
    const windowHeight = window.innerHeight;
    const windowPosition = window.scrollY;

    handleVidePlay(videoHeight, videoPositionTop, windowHeight, windowPosition);
  };

  const handleHeaderShowed = windowPosition => {
    if (windowPosition > 300) {
      setHeaderShowed(false);
    } else {
      setHeaderShowed(true);
    }
  };

  const handleVidePlay = (
    videoHeight,
    videoPositionTop,
    windowHeight,
    windowPosition
  ) => {
    // 影片播放的範圍
    const videoPlayScope =
      windowHeight - (videoPositionTop - windowPosition) > videoHeight * 0.3 &&
      windowPosition - videoPositionTop < videoHeight * 0.7;
    // 影片時間重置為 0 的範圍
    const videoResetScope =
      windowPosition - (videoPositionTop + videoHeight) > 0 ||
      windowPosition + windowHeight - videoPositionTop < 0;

    videoElement.current.play();

    if (videoPlayScope) {
      videoElement.current.play();
    } else {
      videoElement.current.pause();
    }

    if (videoResetScope) {
      videoElement.current.pause();
      videoElement.current.currentTime = 0;
    }
  };

  const handleMouseMove = e => {
    const mousePosition = e.clientY;
    const photoPositionTop = photosElement.current.offsetTop;
    const windowPosition = window.scrollY;

    if (mousePosition + windowPosition > photoPositionTop) {
      if (scrollIntoPhotos.current) {
        photosElement.current.scrollIntoView({
          behavior: 'smooth',
        });
      }
      scrollIntoPhotos.current = false;
    } else {
      scrollIntoPhotos.current = true;
    }
  };

  useEffect(() => {
    // 掛載監聽器，監聽 window 的滾動事件
    window.addEventListener('scroll', handleScroll);
    handleScroll();
    // 掛載監聽器，監聽 window size 改變
    window.addEventListener('resize', handleSize);
    // 掛載監聽器，監聽滑鼠位置
    window.addEventListener('mousemove', handleMouseMove);

    return () => {
      window.removeEventListener('scroll', handleScroll);
      window.removeEventListener('resize', handleSize);
      window.removeEventListener('mousemove', handleMouseMove);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Film maker</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div
          className={
            // 當垂直滾動超過300px時，header隱藏起來
            headerShowed ? styles.headerDisplay : styles.headerDisplay__hidden
          }
        >
          <Header />
        </div>
        <section className={styles.cards}>
          <Cards />
        </section>
        <div className={styles.description1}>
          <p>
            We love to visualize stories because we love people and they inspire
            us.
          </p>
        </div>
        <section className={styles.video}>
          <Video videoRef={videoElement} />
        </section>
        <div className={styles.description2}>
          <p>
            We are a creative agency, film production, branded & original
            content creators.
          </p>
        </div>
        <section>
          <Photos photosRef={photosElement} photosElement={photosElement} />
        </section>
      </main>
    </>
  );
}
