import Head from 'next/head';

import Header from '@/components/Header';
import ShuffleCards from '@/components/ShuffleCards';
import Video from '@/components/Video';
import HorizontalCards from '@/components/HorizontalCards';

import styles from '@/styles/Home.module.scss';

export default function Home() {
  return (
    <>
      <Head>
        <title>Film maker</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <header>
          <Header />
        </header>
        <section className={styles.cards}>
          <ShuffleCards />
        </section>
        <div className={styles.description1}>
          <p>
            We love to visualize stories because we love people and they inspire
            us.
          </p>
        </div>
        <section className={styles.video}>
          <Video />
        </section>
        <div className={styles.description2}>
          <p>
            We are a creative agency, film production, branded & original
            content creators.
          </p>
        </div>
        <section>
          <HorizontalCards />
        </section>
      </main>
    </>
  );
}
