import { useState, useEffect, useRef } from 'react';
import Head from 'next/head';

import Header from '@/components/Header';
import Cards from '@/components/Cards';
import Video from '@/components/Video';
import Photos from '@/components/Photos';

import {
  handleHeaderShowed,
  handleVideoPlay,
  handleMouseInPhotos,
} from '@/utils/handleFunc';

import styles from '@/styles/Home.module.scss';

export default function Home() {
  const [headerShowed, setHeaderShowed] = useState(true);
  const videoElement = useRef();
  const photosElement = useRef();
  const mouseInPhotos = useRef(true);

  const handleScroll = () => {
    const videoHeight = videoElement.current?.clientHeight;
    const videoPositionTop = videoElement.current?.offsetTop;
    const windowHeight = window.innerHeight;
    const windowPosition = window.scrollY;

    handleHeaderShowed(windowPosition, setHeaderShowed);
    handleVideoPlay(
      videoElement.current,
      videoHeight,
      videoPositionTop,
      windowHeight,
      windowPosition
    );
  };

  const handleSize = () => {
    const videoHeight = videoElement.current?.clientHeight;
    const videoPositionTop = videoElement.current?.offsetTop;
    const windowHeight = window.innerHeight;
    const windowPosition = window.scrollY;

    handleVideoPlay(
      videoElement.current,
      videoHeight,
      videoPositionTop,
      windowHeight,
      windowPosition
    );
  };

  const handleMouseMove = e => {
    const mousePosition = e.clientY;
    const photoPositionTop = photosElement.current?.offsetTop;
    const windowPosition = window.scrollY;

    handleMouseInPhotos(
      mouseInPhotos.current,
      photosElement.current,
      mousePosition,
      photoPositionTop,
      windowPosition
    );
  };

  useEffect(() => {
    // 掛載監聽器，監聽 window 的滾動事件
    window.addEventListener('scroll', handleScroll);
    // 掛載監聽器，監聽 window size 改變
    window.addEventListener('resize', handleSize);
    // 掛載監聽器，監聽滑鼠位置
    window.addEventListener('mousemove', handleMouseMove);

    return () => {
      window.removeEventListener('scroll', handleScroll);
      window.addEventListener('wheel', handleScroll);
      window.removeEventListener('resize', handleSize);
      window.removeEventListener('mousemove', handleMouseMove);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Film maker</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div
          className={
            headerShowed ? styles.headerDisplay : styles.headerDisplay__hidden
          }
        >
          <Header />
        </div>
        <section className={styles.cards}>
          <Cards />
        </section>
        <div className={styles.description1}>
          <p>
            We love to visualize stories because we love people and they inspire
            us.
          </p>
        </div>
        <section className={styles.video}>
          <Video videoRef={videoElement} />
        </section>
        <div className={styles.description2}>
          <p>
            We are a creative agency, film production, branded & original
            content creators.
          </p>
        </div>
        <section>
          <Photos photosRef={photosElement} photosElement={photosElement} />
        </section>
      </main>
    </>
  );
}
